image: python:3.10


stages:
  - build
  - deploy


build:
  stage: build
  before_script:
    - pip install -U pip
    - pip install poetry
    - poetry install
  script:
    - poetry run mkdocs build -d public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo 'Skip script section' 
  artifacts:
    paths:
      - public
  only:
    - main

