site_name: pyscript
docs_dir: docs

theme:
  font: false
  name: 'material'
  sticky-navigation: true
  custom_dir: custom_theme

extra_css:
  - "https://pyscript.net/latest/pyscript.css"

extra_javascript:
  - js/extra.js
  - "https://pyscript.net/latest/pyscript.js"
  - "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
  - "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
  - "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"

markdown_extensions:
  - attr_list  # additinal attributes
  - md_in_html # using md in html via <... markdown>

nav:
  - index.md

