site_name: pyscript
docs_dir: docs

theme:
  font: false
  name: 'material'
  sticky-navigation: true
  custom_dir: custom_theme

#extra_css:
#  - "https://pyscript.net/latest/pyscript.css"

extra_javascript:
  - js/extra.js
#  - "https://pyscript.net/latest/pyscript.js"

markdown_extensions:
  - attr_list  # additinal attributes
  - md_in_html # using md in html via <... markdown>

nav:
  - index.md

